// Generated by Wrangler on Fri Aug 23 2024 17:54:35 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	DB: D1Database;
	QUEUE: Queue;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
