#:schema node_modules/wrangler/config-schema.json
name = "rag-uploads"
main = "src/index.ts"
compatibility_date = "2024-08-21"

node_compat = true
logpush = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "rag-uploads"
database_id = "a0863b6a-ef23-4225-83fc-a54a5103e1db"

[[vectorize]]
binding = "VECTORIZE"
index_name = "rag-uploads"

[[queues.producers]]
  queue = "rag-uploads"
  binding = "QUEUE"

[[queues.consumers]]
  queue = "rag-uploads"
  max_batch_size = 1
  max_batch_timeout = 50
